name: hse-tasks
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - beautifulsoup4
  - ipykernel
  - matplotlib
  - networkx
  - numpy
  - pandas
  - requests
  - seaborn
  - scipy
  - pip
  - pip:
      - html5lib
      - lxml
      - openpyxl
      - tqdm
